sudo: false
dist: trusty

branches:
    except:
        - l10n_develop
        - appveyor

language: cpp

cache:
    ccache: true

os: linux

compiler:
    - gcc
    # - clang  # Wait till Clang 6 or patched 5 to work w/ libstdc++.

env:
    global:
        - PATH=$HOME/.local/bin:$PATH:$PWD/install/bin
        - QT_QPA_FONTDIR=/usr/share/fonts
        - QT_QPA_PLATFORM=offscreen
        - GCC_VERSION=7
        - PYTHON_VERSION=3
    matrix:
        - CONFIG=Debug
        - CONFIG=Release

addons:
    apt:
        packages:
            - gcc-7
            - g++-7
            - ccache
            - libboost-program-options1.61-dev
            - libboost-math1.61-dev
            - libboost-random1.61-dev
            - libboost-filesystem1.61-dev
            - libxml2-dev
            - libgoogle-perftools-dev
            - qt59base
            - qt59tools
            - qt59svg
            - fontconfig
            - lcov
        sources: &Sources
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:rakhimov/boost"
            - sourceline: "ppa:zerebubuth/ccache"
            - sourceline: "ppa:beineri/opt-qt593-trusty"

jobs:
    include:
        - stage: lint
          compiler: clang
          before_script: mkdir build
          script: .travis/lint.sh
          env: CONFIG=Lint CLANG_VERSION=6.0
          addons:
              apt:
                  packages:
                      - clang-format-6.0
                      - doxygen
                  sources:
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-trusty-6.0
                      - sourceline: "ppa:rakhimov/doxygen"
        # - stage: test
        #   os: osx  # OS X builds are slow and limited.
        #   osx_image: xcode9.2 # C++17 not yet fully supported!!!
        #   compiler: clang
        #   env: CONFIG=Release
        - stage: test
          compiler: gcc
          env: CONFIG=Coverage
        - stage: test
          compiler: gcc
          env: CONFIG=Memcheck
          before_script: mkdir build install
          addons:
              apt:
                  packages:
                      - gcc-7
                      - g++-7
                      - libboost-program-options1.61-dev
                      - libboost-math1.61-dev
                      - libboost-random1.61-dev
                      - libboost-filesystem1.61-dev
                      - libxml2-dev
                      - valgrind
                  sources: *Sources
    exclude:
        - compiler: gcc
          env: CONFIG=Debug

stages:
    - lint
    - test

before_install:
    - mkdir -p ~/.local/bin
    - virtualenv -p $(which python$PYTHON_VERSION) pyenv
    - source pyenv/bin/activate

install:
    - .travis/install.sh  # Dependencies are built with gcc or clang.

before_script:
    - mkdir build install
    - source /opt/qt59/bin/qt59-env.sh

script:
    - .travis/script.sh
